
class BunchException(Exception):
    """
    BunchException
    ==============

    The BunchException is an exception class used for all exceptions
    generated by the test framework.
    """

    pass
  