
class BunchException(Exception):
    """
    BunchException
    ==============

    The BunchException is an exception class used for all exceptions
    generated by the test framework.
    """

    pass


class CyclicDependencySpecification(BunchException):
    """
    Thrown when it is impossible to figure out linear sequence of execution
    for test fixtures.
    """
    pass